name: Tests & Code Coverage

on:
  push:
    branches:
      - master
      - develop
      - "release/*"
  pull_request:
    branches:
      - develop
      - master
    types:
      - opened
      - synchronize

permissions:
  contents: read

jobs:
  upload-code-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install Dependencies
        env:
          HUSKY: 0
        run: npm run setup

      - name: Run Tests
        run: npm run test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@ab904c41d6ece82784817410c45d8b8c02684457 # v3.1.6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
